adobe/aepsdk-analytics-ios

- AEPAnalytics/Tests/FunctionalTests/AnalyticsConsequenceTests.swift
- AEPAnalytics/Tests/FunctionalTests/AnalyticsFunctionalTestBase.swift
- AEPAnalytics/Tests/FunctionalTests/AnalyticsHitReorderTests.swift
- AEPAnalytics/Tests/FunctionalTests/AnalyticsIDTests.swift
- AEPAnalytics/Tests/FunctionalTests/AnalyticsTrack+ConfigurationTests.swift
- AEPAnalytics/Tests/FunctionalTests/AnalyticsTrack+LifecycleTests.swift
- AEPAnalytics/Tests/FunctionalTests/AnalyticsTrack+PlacesTests.swift
- AEPAnalytics/Tests/FunctionalTests/AnalyticsTrackTests.swift
Analytics hit reordering functional tests
Scenarios around lifecycle, acquisition and custom track state/action
> Analytics hit reordering tests

- AEPAnalytics/Sources/AnalyticsTimer.swift
- Makefile
Include simulator frameworks when building archive. 
Fix errors when including as SPM dependency
> Fix build issues

- AEPAnalytics/Sources/Analytics.swift
- AEPAnalytics/Sources/AnalyticsTimer.swift
> Refactor code and update doc comments

- AEPAnalytics.podspec
> Update version in podspec

- .github/workflows/release.yml
- AEPAnalytics.podspec
- AEPAnalytics.xcodeproj/project.pbxproj
- AEPAnalytics/Sources/Analytics.swift
- AEPAnalytics/Sources/AnalyticsConstants.swift
- AEPAnalytics/Sources/AnalyticsTimer.swift
- AEPAnalytics/Tests/FunctionalTests/AnalyticsTrack+TargetTests.swift
- Podfile.lock
- Script/test-SPM.sh
- Script/test-podspec.sh
- Script/version.sh
> Dev v3.0.1 to Main for 3.0.1 release

- Makefile
> add makefile commands for release

- .circleci/config.yml
- AEPAnalytics.xcodeproj/project.pbxproj
- AEPAnalytics/Tests/TestHelper/MockExtension.swift
- AEPAnalytics/Tests/TestHelper/TestableExtensionRuntime.swift
- Package.swift
- Podfile.lock
- README.md
Add AEPAnalytics.framework to SampleApp to fix an relaunch issue.
> Add AEPAnalytics.framework to SampleAPP

- README.md
> Update SPM readme

- .circleci/config.yml
- .gitignore
- AEPAnalytics.xcodeproj/project.pbxproj
- AEPAnalytics/Sources/Analytics.swift
- AEPAnalytics/Sources/ContextDataUtil.swift
- AEPAnalytics/Tests/FunctionalTests/AnalyticsFunctionalTestBase.swift
- AEPAnalytics/Tests/FunctionalTests/AnalyticsTrack+AssuranceTests.swift
- AEPAnalytics/Tests/TestHelper/MockExtension.swift
- AEPAnalytics/Tests/TestHelper/TestHelper.swift
- AEPAnalytics/Tests/TestHelper/TestableExtensionRuntime.swift
- AEPAnalytics/Tests/UnitTests/AnalyticsHitProcessorTests.swift
- Package.swift
- Podfile
- Podfile.lock
- README.md
Including changes for updating SMP,  tests and code coverage scripts
> Merge dev to main branch - changes for updating SMP,  tests and code coverage scripts

- AEPAnalytics/Sources/Analytics.swift
- AEPAnalytics/Tests/FunctionalTests/AnalyticsTrackTests.swift
> [MOB-14992] Clean Analytics context data. 

- AEPAnalytics.podspec
- AEPAnalytics.xcodeproj/project.pbxproj
- AEPAnalytics/Sources/Analytics+PublicAPI.swift
- AEPAnalytics/Sources/AnalyticsConstants.swift
- AEPAnalytics/Sources/Info.plist
- AEPAnalytics/Tests/UnitTests/AnalyticsAPITests.swift
- AnalyticsSampleApp/AnalyticsView.swift
- AnalyticsSampleApp/AppDelegate.swift
- Makefile
- Podfile
- Podfile.lock
> Fix public API completion error code and update test app

- .circleci/config.yml
- .gitignore
- AEPAnalytics.podspec
- AEPAnalytics.xcodeproj/project.pbxproj
- AEPAnalytics/Sources/Analytics+PublicAPI.swift
- AEPAnalytics/Sources/Analytics.swift
- AEPAnalytics/Sources/AnalyticsConstants.swift
- AEPAnalytics/Sources/ContextDataUtil.swift
- AEPAnalytics/Sources/Info.plist
- AEPAnalytics/Tests/FunctionalTests/AnalyticsFunctionalTestBase.swift
- AEPAnalytics/Tests/FunctionalTests/AnalyticsTrack+AssuranceTests.swift
- AEPAnalytics/Tests/FunctionalTests/AnalyticsTrackTests.swift
- AEPAnalytics/Tests/TestHelper/MockExtension.swift
- AEPAnalytics/Tests/TestHelper/TestHelper.swift
- AEPAnalytics/Tests/TestHelper/TestableExtensionRuntime.swift
- AEPAnalytics/Tests/UnitTests/AnalyticsAPITests.swift
- AEPAnalytics/Tests/UnitTests/AnalyticsHitProcessorTests.swift
- AnalyticsSampleApp/AnalyticsView.swift
- AnalyticsSampleApp/AppDelegate.swift
- Documentation/AEPAnalytics.md
- Makefile
- Package.swift
- Podfile
- Podfile.lock
- README.md
> dev -> staging (v3.0.2)

- AEPAnalytics/Sources/Analytics.swift
- AEPAnalytics/Sources/AnalyticsConstants.swift
- AEPAnalytics/Sources/AnalyticsMigrator.swift
- AEPAnalytics/Sources/AnalyticsProperties.swift
- AEPAnalytics/Sources/URL+Analytics.swift
- AEPAnalytics/Tests/FunctionalTests/AnalyticsFunctionalTestBase.swift
- AEPAnalytics/Tests/FunctionalTests/AnalyticsIDTests.swift
- AEPAnalytics/Tests/TestHelper/AnalyticsTestConstants.swift
- AEPAnalytics/Tests/UnitTests/AnalyticsMigratorTests.swift
- AEPAnalytics/Tests/UnitTests/URL+AnalyticsTests.swift
- Documentation/AEPAnalytics.md
> [MOB-14663] Remove AID generation logic.

- .circleci/config.yml
- AEPAnalytics.xcodeproj/project.pbxproj
- Makefile
- Podfile
- Podfile.lock
- README.md
> Update build scripts and add debug symbols to fix the build archive step

- AEPAnalytics.podspec
- AEPAnalytics.xcodeproj/project.pbxproj
- AEPAnalytics/Sources/AnalyticsConstants.swift
> Bump up version for v3.0.4 release

- AEPAnalytics.podspec
- AEPAnalytics.xcodeproj/project.pbxproj
- AEPAnalytics/Sources/AnalyticsConstants.swift
> Version bump for 3.2.0 release

- README.md
> Update latest SPM instruction

- README.md
> Update SPM instruction.

- AEPAnalytics/Sources/Analytics.swift
- Podfile.lock
Update the routing of `resetIdentities` event through the `handleIncomingEvent` handler so that it is handled within the same `DispatchQueue` as all other events, avoiding potential race condition (thanks to Praveen V for identifying this issue!).
> Route resetIdentities event though event handler to avoid potential data race

- AEPAnalytics.xcodeproj/project.pbxproj
- AEPAnalytics/Sources/AnalyticsConstants.swift
- AEPAnalytics/Tests/FunctionalTests/AnalyticsTrack+LifecycleTestBase.swift
- AEPAnalytics/Tests/TestHelper/AnalyticsTestConstants.swift
- Podfile.lock
in alignment with https://github.com/adobe/aepsdk-core-ios/pull/935 - this pr grabs the new value from lifecycle and adds it to the outgoing lifecycle hit for analytics
> -support system locale in lifecycle hit to analytics

- AEPAnalytics.xcodeproj/project.pbxproj
- Podfile
Update Podfile branch version and merge from main branch.
> Update Podfile branch version and merge from main

- Package.swift
- Podfile.lock
> Update pods + swift-tools-version 5.3

- Podfile
- Podfile.lock
> pod update

- .github/workflows/update_versions.yml
- Script/update-versions.sh
> Add Github action workflow to update version automatically

- AEPAnalytics.podspec
- AEPAnalytics.xcodeproj/project.pbxproj
- AEPAnalytics/Sources/AnalyticsConstants.swift
- Script/update-versions.sh
> Updating version to 5.1.0

- .github/workflows/update_versions.yml
- AEPAnalytics.podspec
- Package.swift
- Podfile
- Podfile.lock
> Remove explicit AEPServices dependency

- AEPAnalytics.podspec
- AEPAnalytics.xcodeproj/project.pbxproj
- AEPAnalytics/Sources/AnalyticsConstants.swift
- Script/update-versions.sh
> Update version to 5.0.1

- AEPAnalytics.podspec
- AEPAnalytics.xcodeproj/project.pbxproj
- AEPAnalytics/Sources/AnalyticsConstants.swift
- Script/update-versions.sh
> Update version to 5.0.1 
